### ISSUE TITLE
PS4 save game dump: tag parsing errors

### ISSUE THREAD

**Issue by vansoest** [abramhindle/ttwl-cli-saveedit#16]
Hi, I have just dumped our save files from our PS4 to continue playing on a steam gaming pc. I dumped them 2 times to have a not corrupted dump. Installed the dev build via pip inside Arch Linux, BTW.

So the header is PS4, found your tools to hopefully convert them to windows. I have read I can convert them to JSON, then patch the JSON and convert it back to a save game.

```
00000000: 47 56 41 53 02 00 00 00 04 02 00 00 04 00 14 00  GVAS............
00000010: 03 00 89 a5 2b 80 16 00 00 00 44 41 46 46 4f 44  ....+.....DAFFOD
00000020: 49 4c 2d 50 41 54 43 48 50 53 34 31 2d 37 31 00  IL-PATCHPS41-71.
```

https://filepickup.phcn.de/sophie_ps4_export.sav

```
$ ttwl-save-info -i sophie_ps4_export.sav 
Traceback (most recent call last):
  File "/home/sophie/.local/bin/ttwl-save-info", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/sophie/.local/lib/python3.11/site-packages/ttwlsave/cli_info.py", line 85, in main
    save = TTWLSave(args.filename)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophie/.local/lib/python3.11/site-packages/ttwlsave/ttwlsave.py", line 190, in __init__
    self.import_protobuf(data)
  File "/home/sophie/.local/lib/python3.11/site-packages/ttwlsave/ttwlsave.py", line 205, in import_protobuf
    raise Exception('Unable to parse savegame (did you pass a profile, instead?): {}'.format(e)) from None
Exception: Unable to parse savegame (did you pass a profile, instead?): Wrong wire type in tag.
```

http://filedrop.phcn.de/uploads/profile

```
$ ttwl-profile-info profile 
Traceback (most recent call last):
  File "/home/sophie/.local/bin/ttwl-profile-info", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/sophie/.local/lib/python3.11/site-packages/ttwlsave/cli_prof_info.py", line 63, in main
    prof = TTWLProfile(args.filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sophie/.local/lib/python3.11/site-packages/ttwlsave/ttwlprofile.py", line 176, in __init__
    self.import_protobuf(data)
  File "/home/sophie/.local/lib/python3.11/site-packages/ttwlsave/ttwlprofile.py", line 191, in import_protobuf
    raise Exception('Unable to parse profile (did you pass a savegame, instead?): {}'.format(e)) from None
Exception: Unable to parse profile (did you pass a savegame, instead?): Wrong wire type in tag.
```

Hope someone can check these save if they usable or not complete.

edited: uploaded profile

**Comment by vansoest** [comment]
@abramhindle any ideas?
